apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-no-configmap
  labels:
    app: nginx-no-configmap
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx-no-configmap
  template: 
    metadata: 
      labels: 
        app: nginx-no-configmap 
    spec: 
      containers: 
      - name: nginx-no-configmap 
        image: quay.io/nginx/nginx-unprivileged:stable-alpine
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: "/usr/share/nginx/html"
      volumes:
      - name: config
        configMap:
          name: myconfigmap
