apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-badimage
  labels:
    app: nginx-badimage
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nginx-badimage
  template: 
    metadata: 
      labels:
        app: nginx-badimage 
    spec: 
      containers: 
      - name: nginx-badimage 
        image: quay.io/nginx/nginx-unprivilegedoops:stable-alpine
        ports: 
        - containerPort: 80
