apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: veryfaststorage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi-driver.bad-csi-driver.example
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-nopv
  labels:
    app: nginx-nopv
spec: 
  containers: 
  - name: nginx 
    image: quay.io/nginx/nginx-unprivileged:stable-alpine
    ports: 
    - containerPort: 80
    volumeMounts:
    - name: config
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: pvcforme
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcforme
spec:
  storageClassName: veryfaststorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi