---
apiVersion: v1 
kind: Namespace
metadata: 
  name: mynamespace
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: memsstresslow 
  namespace: mynamespace
  labels:
    app: stress  
spec: 
  containers: 
  - name: stress 
    image: progrium/stress
    command: ["stress", "--cpu", "2", "--io", "1", "--vm", "1", "--vm-bytes", "128M", "--timeout", "60s"]