---
apiVersion: v1 
kind: Namespace
metadata: 
  name: mynamespace
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-nopvc
  namespace: mynamespace
  labels:
    app: nginx-nopvc
spec: 
  containers: 
  - name: nginx 
    image: nginx:1.27.0
    ports: 
    - containerPort: 80
    volumeMounts:
    - name: config
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: mypvc