---
apiVersion: v1 
kind: Namespace
metadata: 
  name: mynamespace
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: memstresshigh
  namespace: mynamespace
  labels:
    app: stress  
spec: 
  containers: 
  - name: stress 
    image: progrium/stress
    command: ["stress", "--cpu", "1", "--io", "1", "--vm", "1", "--vm-bytes", "1280M", "--timeout", "300s"]
    resources:
      requests:
        cpu: 1100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 256Mi
  tolerations:
  - key: "high-mem-node"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  restartPolicy: Always