apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-nopvc
  labels:
    app: nginx-nopvc
spec: 
  containers: 
  - name: nginx 
    image: quay.io/nginx/nginx-unprivleged:stable-alpine
    ports: 
    - containerPort: 80
    volumeMounts:
    - name: config
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: mypvc