apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-scnotexist
  labels:
    app: nginx-scnotexist
spec: 
  containers: 
  - name: nginx 
    image: quay.io/nginx/nginx-unprivileged:stable-alpine
    ports: 
    - containerPort: 80
    volumeMounts:
    - name: config
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: mypvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: veryfaststorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi