apiVersion: v1 
kind: Pod 
metadata: 
  name: memstresslow 
  labels:
    app: stress  
spec: 
  containers: 
  - name: stress 
    image: progrium/stress
    command: ["stress", "--cpu", "1", "--io", "1", "--vm", "1", "--vm-bytes", "100M", "--timeout", "300s"]
    resources:
      requests:
        cpu: 1100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 256Mi
  restartPolicy: Always