apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-highmem
  labels:
    app: nginx  
spec: 
  containers: 
  - name: nginx 
    image: quay.io/nginx/nginx-unprivleged:stable-alpine
    ports: 
    - containerPort: 80
    resources:
      requests:
        cpu: 200m
        memory: 128Gi
      limits:
        cpu: 500m
        memory: 256Gi