apiVersion: v1
kind: Pod
metadata:
  name: wordpress-badmysql
  labels:
    app: wordpress-badmysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "mypassword"
  - name: wordpress
    image: wordpress:6.2.1-apache
    ports:
    - containerPort: 80
    securityContext:
      sysctls:
      - name: net.ipv4.ip_unprivileged_port_start
        value: "80"
    volumeMounts:
    - name: wordpress-persistent-storage
      mountPath: /var/www/html
  volumes:
  - name: wordpress-persistent-storage
    persistentVolumeClaim:
      claimName: wp-pv-claim
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-badmysql
  labels:
    app: wordpress-badmysql
spec:
  ports:
    - port: 80
  selector:
    app: wordpress-badmysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi