---
apiVersion: v1 
kind: Namespace
metadata: 
  name: wordpress
---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-badmysql
  labels:
    app: wordpress-badmysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0
  - name: wordpress
    image: wordpress:6.2.1-apache
  restartPolicy: Always